# Generated by Django 4.2.16 on 2026-01-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Tarmoq nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_network/')),
                ('link', models.URLField(null=True, verbose_name="Tarmoq yo'li")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tarmoq haqida')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Social Network',
                'db_table': 'social_network',
                'ordering': ['-created_at'],
            },
        ),
    ]
