# Generated by Django 4.2.16 on 2026-01-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_network/', verbose_name='Rasm'),
        ),
    ]
