# Generated by Django 4.2.16 on 2025-12-27 17:07

import apps.utils.generate_code
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.PositiveBigIntegerField(unique=True)),
                ('username', models.CharField(db_index=True, max_length=200, null=True, unique=True)),
                ('specialization', models.CharField(max_length=255, null=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctors Profile',
                'db_table': 'doctor_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('blocked', 'Blocked')], default='follow', max_length=50)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.PositiveBigIntegerField(db_index=True, default=apps.utils.generate_code.generate_code, unique=True)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('slug', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patients Profile',
                'db_table': 'patient_profile',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.FileField(upload_to='users/profile/story/')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='profile.doctorprofile')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'db_table': 'story',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to='contenttypes.contenttype')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_view', to='profile.story')),
            ],
            options={
                'verbose_name': 'Story View',
                'verbose_name_plural': 'Story Viewers',
                'db_table': 'story_view',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
