# Generated by Django 5.2.7 on 2025-12-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='profile.baseprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profile.baseprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profile.baseprofile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='profile.baseprofile'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_view', to='profile.story'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='view_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to='profile.baseprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='baseprofile',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('profile', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'view_profile')},
        ),
    ]
