# Generated by Django 4.2.16 on 2026-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
