# Generated by Django 4.2.16 on 2026-01-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('content', models.FileField(upload_to='video_reels/', verbose_name='content manzili')),
                ('content_type', models.CharField(choices=[('reels', 'Reels'), ('video', 'Video')], default='reels')),
                ('description', models.TextField(null=True, verbose_name='content haqida malumot')),
                ('thumbnail', models.CharField(null=True, verbose_name='content oblojkasi')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='content davomiyligi')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='korishlar soni')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='likelar soni')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='dislikelar soni')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='jami izohlar soni')),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reels', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video / Reel',
                'verbose_name_plural': 'Video / Reels',
                'db_table': 'video_reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoReelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reels_comments', to='video.videoreels')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='video.videoreelscomment')),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comment', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoReelsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_content', to='video.videoreels')),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_video_reels', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video / Reel/ View',
                'verbose_name_plural': 'Video / Reels/ View',
                'db_table': 'video_reels_view',
                'ordering': ['-created_at'],
                'unique_together': {('profile_content_type', 'profile_obj_id', 'content')},
            },
        ),
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'DisLike')], default='like')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_like_dislike', to='video.videoreels')),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_like_dislike', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video Reaction',
                'verbose_name_plural': 'Video Reaction',
                'db_table': 'video_reaction',
                'ordering': ['-created_at'],
                'unique_together': {('profile_content_type', 'profile_obj_id', 'content')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_obj_id', models.PositiveIntegerField()),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'DisLike')], default='like')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to='video.videoreelscomment')),
                ('profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comment_reaction', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comment Reaction',
                'verbose_name_plural': 'Comment Reactions',
                'db_table': 'comment_reaction',
                'ordering': ['-created_at'],
                'unique_together': {('profile_content_type', 'profile_obj_id', 'comment')},
            },
        ),
    ]
