# Generated by Django 4.2.16 on 2026-01-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreels',
            name='content_type',
            field=models.CharField(choices=[('reels', 'Reels'), ('video', 'Video')], db_index=True, default='reels'),
        ),
        migrations.AlterField(
            model_name='videoreels',
            name='description',
            field=models.TextField(db_index=True, null=True, verbose_name='content haqida malumot'),
        ),
        migrations.AlterField(
            model_name='videoreelsview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
