# Generated by Django 4.2.16 on 2026-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_videoreels_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoreelscomment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoreelscomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
