# Generated by Django 4.2.16 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_commentreaction_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
