# Generated by Django 4.2.16 on 2026-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videoreels_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreels',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
