# Generated by Django 4.2.16 on 2026-01-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0005_videoreels_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreelscomment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoreels',
            name='content_type',
            field=models.CharField(choices=[('reels', 'Reels'), ('video', 'Video')], db_index=True, default='reels', verbose_name='Content turi'),
        ),
        migrations.AlterField(
            model_name='videoreels',
            name='profile_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reels', to='contenttypes.contenttype', verbose_name='Content egasi'),
        ),
        migrations.AlterField(
            model_name='videoreels',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='', verbose_name='content oblojkasi'),
        ),
    ]
