# Generated by Django 4.2.16 on 2026-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videoreelscomment_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='videoreelscomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
