# Generated by Django 4.2.16 on 2026-01-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_commentreaction_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreels',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='video_reels/thumbnail/', verbose_name='content oblojkasi'),
        ),
    ]
