# Generated by Django 4.2.16 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_videoreels_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreels',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='', verbose_name='content oblojkasi'),
        ),
    ]
