# Generated by Django 4.2.16 on 2026-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_active_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='_type',
            field=models.CharField(choices=[('register', 'register'), ('change-password', 'change password'), ('update-contact', 'update-contact')], max_length=50, null=True),
        ),
    ]
