"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta

import decouple
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple.config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config('DEBUG')

ALLOWED_HOSTS = decouple.config('ALLOWED_HOSTS', cast=decouple.Csv())

# Application definition
CUSTOM_APPS = [
    'apps.super_admin',
    'apps.users',
    'apps.profile',
    'apps.video',
    'apps.order',
    'apps.banner',
    'apps.service',
    'apps.history',
]

CUSTOM_INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'background_task',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

]

INSTALLED_APPS = [
                     'django.contrib.admin',
                     'django.contrib.auth',
                     'django.contrib.contenttypes',
                     'django.contrib.sessions',
                     'django.contrib.messages',
                     'django.contrib.staticfiles',
                 ] + CUSTOM_INSTALLED_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': decouple.config("DB_NAME"),
        'USER': decouple.config("DB_USER"),
        'PASSWORD': decouple.config("DB_PASS"),
        'HOST': decouple.config('DB_HOST'),
        'PORT': decouple.config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', "O'zbekcha"),
    ('ru', 'Russian'),
    ('en', 'English')
]
USE_I18N = True
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'Asia/Tashkent'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
    'EXCEPTION_HANDLER': 'apps.utils.custom_permission.custom_exception_handler',

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    'AUTH_HEADER_TYPES': ('Bearer',),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# EMAIL
EMAIL_BACKEND = decouple.config('EMAIL_BACKEND')
EMAIL_HOST = decouple.config('EMAIL_HOST')
EMAIL_PORT = decouple.config('EMAIL_PORT')
EMAIL_USE_TLS = decouple.config('EMAIL_USE_TLS')
EMAIL_HOST_USER = decouple.config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = decouple.config('EMAIL_HOST_PASSWORD')

SPECTACULAR_SETTINGS = {
    'TITLE': 'Sinon API',
    'DESCRIPTION': 'Sinon API documentation',
    'VERSION': 'v1',
    'COMPONENT_SPLIT_REQUEST': True,
}


# APPLE KEY
TEAM_ID = decouple.config('TEAM_ID')
CLIENT_ID = decouple.config('CLIENT_ID')
KEY_ID = decouple.config('KEY_ID')
PRIVATE_KEY = decouple.config('PRIVATE_KEY')

SOCIAL_AUTH_KEYS = {
    "GOOGLE": {
        "GOOGLE_CLIENT_ID": decouple.config('GOOGLE_CLIENT_ID'),
        "GOOGLE_SECRET": decouple.config('GOOGLE_SECRET')
    },
    "FACEBOOK": {
        "FACEBOOK_CLIENT_ID": decouple.config('FACEBOOK_CLIENT_ID'),
        "FACEBOOK_SECRET": decouple.config('FACEBOOK_SECRET')
    },
    "APPLE": {
        "APPLE_CLIENT_ID": decouple.config('APPLE_CLIENT_ID'),
        "APPLE_CLIENT_SECRET": decouple.config('APPLE_CLIENT_SECRET'),
        "APPLE_PUBLIC_URL": decouple.config("APPLE_PUBLIC_URL")
    },
    "REDIRECT_URI": decouple.config('REDIRECT_URI')

}

CORS_ALLOWED_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False

APPEND_SLASH = True
