# Generated by Django 4.2.16 on 2026-01-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='add_patient/')),
                ('gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], default='erkak')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_patients', to='profile.patientprofile')),
            ],
            options={
                'verbose_name': 'Add Patient',
                'verbose_name_plural': 'Add Patients',
                'db_table': 'add_patient',
                'ordering': ['-created_at'],
            },
        ),
    ]
