# Generated by Django 4.2.16 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='add_patient/'),
        ),
    ]
