# Generated by Django 4.2.16 on 2026-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='_type',
            field=models.CharField(choices=[('elon', 'Elon'), ('link', 'Link')], db_index=True, default='elon'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
