# Generated by Django 4.2.16 on 2026-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner__type_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
