# Generated by Django 4.2.16 on 2026-01-08 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='doctor_application/doctor_image/')),
                ('region', models.CharField(db_index=True, max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')])),
                ('passport', models.CharField(max_length=20)),
                ('passport_image', models.ImageField(upload_to='doctor_application/passport_image/')),
                ('passport_image2', models.ImageField(upload_to='doctor_application/passport_image2/')),
                ('diplom_image', models.ImageField(upload_to='doctor_application/diplom_image/')),
                ('bio', models.TextField()),
                ('term', models.DateField()),
                ('status', models.CharField(choices=[('pendingPending', 'Pending'), ('approvedApproved', 'Approved'), ('cancelledCancelled', 'Cancelled')], default='pendingPending', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Application',
                'verbose_name_plural': 'Doctor Applications',
                'db_table': 'doctor_application',
                'ordering': ['created_at'],
            },
        ),
    ]
