# Generated by Django 4.2.16 on 2026-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='experience_year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='term',
            field=models.DateField(null=True),
        ),
    ]
