# Generated by Django 4.2.16 on 2026-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_application', '0002_doctorapplication_experience_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='speciality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='status',
            field=models.CharField(choices=[('pendingPending', 'Pending'), ('approvedApproved', 'Approved'), ('cancelledCancelled', 'Cancelled'), ('finishedFinished', 'Finished')], default='pendingPending', max_length=50),
        ),
    ]
