# Generated by Django 4.2.16 on 2026-01-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_application', '0003_doctorapplication_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='term',
            field=models.DateTimeField(null=True),
        ),
    ]
