# Generated by Django 4.2.16 on 2026-01-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_doctorprofile_status'),
        ('history', '0002_rename_city_address_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil turi'),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Qavat'),
        ),
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bino raqami'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kirish eshik raqami'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Uy raqami'),
        ),
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.patientprofile', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ko'cha"),
        ),
    ]
