# Generated by Django 4.2.16 on 2026-01-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_doctorprofile_status'),
        ('history', '0003_address_address_type_address_floor_address_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_address', to='profile.patientprofile', verbose_name='Bemor'),
        ),
    ]
